name: Test build for emerald_ble as external component
on:
  push:
  pull_request:

jobs:
  build:
    name: ${{matrix.python}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python:
          - 3.12

    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python}}
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: 'test-as-external-requirements.txt'

      - name: Install esphome
        run: pip install -r test-as-external-requirements.txt

      - uses: actions/cache@v3
        id: esphome-cache # use this to check for `cache-hit` ==> if: steps.esphome-cache.outputs.cache-hit != 'true'
        with:
          path: |
            test/.esphome/**
            $HOME/.platformio/**
          key: ${{ matrix.os }}-${{matrix.python}}-esphome

      - name: Check config
        run: esphome config tests/*emerald*.yaml

      - name: Build
        run: esphome compile tests/*emerald*.yaml
